### ISSUE TITLE
Failed to run command steganogan encode

### ISSUE THREAD

**Issue by mrliliang** [DAI-Lab/SteganoGAN#42]
* SteganoGAN version or git commit:

* Python version (output of `python --version`):
  Python 3.7.0
* Pip version (output of `pip --version`):
   pip 10.0.1 from /usr/local/python3.7/lib/python3.7/site-packages/pip (python 3.7)
* Operating System: 
   MacOS 10.14.4
### Description

I installed SteganoGAN by pip, and just try to test the command **steganogan encode** to encode some text to an image, but the command failed and some error happened.

### What I Did
Firstly, install SteganoGAN by pip.
Sencondly, run command
**steganogan encode -a dense research/input.png "Message to hide"**  
Thirdly, errors happened.

All command and errors are as follows
1. pip3 install steganogan, succeed.
2. steganogan encode -a dense research/input.png "Message to hide",  failed as follows

Traceback (most recent call last):
  File "/Users/liliang/PycharmProjects/SteganoGAN-master/venv/bin/steganogan", line 10, in <module>
    sys.exit(main())
  File "/Users/liliang/PycharmProjects/SteganoGAN-master/venv/lib/python3.7/site-packages/steganogan/cli.py", line 88, in main
    args.action(args)
  File "/Users/liliang/PycharmProjects/SteganoGAN-master/venv/lib/python3.7/site-packages/steganogan/cli.py", line 26, in _encode
    steganogan.encode(args.cover, args.output, args.message)
  File "/Users/liliang/PycharmProjects/SteganoGAN-master/venv/lib/python3.7/site-packages/steganogan/models.py", line 304, in encode
    generated = self.encoder(cover, payload)[0].clamp(-1.0, 1.0)
  File "/Users/liliang/PycharmProjects/SteganoGAN-master/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/liliang/PycharmProjects/SteganoGAN-master/venv/lib/python3.7/site-packages/steganogan/encoders.py", line 58, in forward
    x = self._models[0](image)
  File "/Users/liliang/PycharmProjects/SteganoGAN-master/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/liliang/PycharmProjects/SteganoGAN-master/venv/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/Users/liliang/PycharmProjects/SteganoGAN-master/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/liliang/PycharmProjects/SteganoGAN-master/venv/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 331, in forward
    if self.padding_mode == 'circular':
  File "/Users/liliang/PycharmProjects/SteganoGAN-master/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'Conv2d' object has no attribute 'padding_mode'

**Comment by pvk-developer** [comment]
Hello @mrliliang , would you mind provinding one more detail about your environmet?
We would like to know your `torch` version. To do so, you can run `pip3 freeze | grep torch` which will display such an information.

We believe that the problem comes with a recent release from `torch` (they released the version 1.1.0) and in case that you have the version `1.1.0` we would suggest you to use the version `1.0.0` instead. 

If it is the case that you have the version `1.1.0` you can install the version `1.0.0` by removing `torch` (`pip3 uninstall torch`) and then installing the 1.0.0 version by runing `pip3 install torch==1.0.0` .

**Comment by mrliliang** [comment]
My torch vision 1.1.0, detail is in the following
torch==1.1.0
torchvision==0.2.2.post3

I will try torch 1.0.0, thank you

**Comment by mrliliang** [comment]
> Hello @mrliliang , would you mind provinding one more detail about your environmet?
> We would like to know your `torch` version. To do so, you can run `pip3 freeze | grep torch` which will display such an information.
> 
> We believe that the problem comes with a recent release from `torch` (they released the version 1.1.0) and in case that you have the version `1.1.0` we would suggest you to use the version `1.0.0` instead.
> 
> If it is the case that you have the version `1.1.0` you can install the version `1.0.0` by removing `torch` (`pip3 uninstall torch`) and then installing the 1.0.0 version by runing `pip3 install torch==1.0.0` .

Your are right, torch 1.0.0 works well. Thank you.

**Comment by pvk-developer** [comment]
> You are right, torch 1.0.0 works well. In addition, I think it might be better to write your environment configuration in Read Me page. Thank you.

Thank you for your feedback @mrliliang , we will updated the `setup.py` to use and require the version `1.0.0`, and also we will update the `README` file in order to inform that we are using the `torch 1.0.0` in case some other user has this same problem.
