### ISSUE TITLE
i can't encode.

### ISSUE THREAD

**Issue by kompowiec** [DAI-Lab/SteganoGAN#96]
* SteganoGAN version or git commit:
* Python version (output of `python --version`): Python 3.12.7
* Pip version (output of `pip --version`): pip 24.3.1 from /usr/lib/python3.12/site-packages/pip (python 3.12)
* PyTorch version (output of `python -c "import torch; print(torch.__version__)"`): 2.3.1
* Operating System: ArcoLinux (Arch linux)

### Description

steganogan encode -v in.png "Hello world" -o out.png 

/home/kompowiec2/myenv/lib/python3.12/site-packages/torch/serialization.py:1113: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/kompowiec2/myenv/lib/python3.12/site-packages/torch/serialization.py:1113: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/kompowiec2/myenv/lib/python3.12/site-packages/torch/serialization.py:1113: SourceChangeWarning: source code of class 'torch.nn.modules.activation.LeakyReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/kompowiec2/myenv/lib/python3.12/site-packages/torch/serialization.py:1113: SourceChangeWarning: source code of class 'torch.nn.modules.batchnorm.BatchNorm2d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/kompowiec2/myenv/lib/python3.12/site-packages/torch/serialization.py:1113: SourceChangeWarning: source code of class 'steganogan.decoders.DenseDecoder' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/kompowiec2/myenv/lib/python3.12/site-packages/torch/serialization.py:1113: SourceChangeWarning: source code of class 'steganogan.critics.BasicCritic' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
Traceback (most recent call last):
  File "/home/kompowiec2/myenv/bin/steganogan", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kompowiec2/myenv/lib/python3.12/site-packages/steganogan/cli.py", line 88, in main
    args.action(args)
  File "/home/kompowiec2/myenv/lib/python3.12/site-packages/steganogan/cli.py", line 25, in _encode
    steganogan = _get_steganogan(args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kompowiec2/myenv/lib/python3.12/site-packages/steganogan/cli.py", line 20, in _get_steganogan
    return SteganoGAN.load(**steganogan_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kompowiec2/myenv/lib/python3.12/site-packages/steganogan/models.py", line 364, in load
    steganogan = torch.load(path, map_location='cpu', weights_only=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kompowiec2/myenv/lib/python3.12/site-packages/torch/serialization.py", line 1040, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kompowiec2/myenv/lib/python3.12/site-packages/torch/serialization.py", line 1272, in _legacy_load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "/home/kompowiec2/myenv/lib/python3.12/site-packages/torch/optim/adam.py", line 66, in __setstate__
    super().__setstate__(state)
  File "/home/kompowiec2/myenv/lib/python3.12/site-packages/torch/optim/optimizer.py", line 313, in __setstate__
    self.defaults.setdefault('differentiable', False)
    ^^^^^^^^^^^^^
AttributeError: 'Adam' object has no attribute 'defaults'

### What I Did
i modify steganogan/models.py:

steganogan = torch.load(path, map_location='cpu', weights_only=False)

ERROR: Could not find a version that satisfies the requirement torch==1.8.1 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
ERROR: No matching distribution found for torch==1.8.1

2. Traceback (most recent call last):
  File "/home/kompowiec2/myenv/bin/steganogan", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kompowiec2/myenv/lib/python3.12/site-packages/steganogan/cli.py", line 88, in main
    args.action(args)
  File "/home/kompowiec2/myenv/lib/python3.12/site-packages/steganogan/cli.py", line 25, in _encode
    steganogan = _get_steganogan(args)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kompowiec2/myenv/lib/python3.12/site-packages/steganogan/cli.py", line 20, in _get_steganogan
    return SteganoGAN.load(**steganogan_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kompowiec2/myenv/lib/python3.12/site-packages/steganogan/models.py", line 364, in load
    steganogan = torch.load(path, map_location='cpu', weights_only=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kompowiec2/myenv/lib/python3.12/site-packages/torch/serialization.py", line 1383, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint.
	(1) Re-running torch.load with weights_only set to False will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with weights_only=True please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL steganogan.models.SteganoGAN was not an allowed global by default. Please use torch.serialization.add_safe_globals([SteganoGAN]) to allowlist this global if you trust this class/function.

I don't know what else I can do. Model training works for me.

**Comment by bbtx2024** [comment]
i ask gpt how to deal with it.
gpt told me to use docker
and i create a docker with python3.6 and encode successful.
now i cant decode
<img width="773" alt="image" src="https://github.com/user-attachments/assets/762fbae0-3a5e-459f-bdd4-2f91ba5e7553">

**Comment by kompowiec** [comment]
I also used chatgpt but they just suggested weights_only=False)

> and i create a docker with python3.6 and encode successful.

now it's makes sense. I had no idea what version of python it required. As for torch, I'll probably have to manually download it from another source.

**Comment by RDadsetan** [comment]
For any friends wants to use this library should notice that it says it needs torch1.0.0 so you must use this version of torch as it require

but you i get torch1.0.0 in pypi and pytorch official website, it didn't work properly so I recommend use library.io and sorce forge 

also you might faced the issue about cuda, I recommend to un enable it

**Comment by kompowiec** [comment]
ok i think i figure out for debian:

[Quick setup guide for pyenv + Python 3.7](https://bgasparotto.com/install-pyenv-ubuntu-debian)

1. **Install dependencies for building Python**
   (Needed to compile Python from source)

```bash
sudo apt update
sudo apt install -y build-essential curl libssl-dev zlib1g-dev \
libbz2-dev libreadline-dev libsqlite3-dev wget llvm libncurses5-dev \
libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
```

2. **Install pyenv**

```bash
curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
```

3. **Configure your shell environment**
   Add to your `.bashrc` or `.zshrc`:

```bash
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - bash)"
```

Then reload your shell:

```bash
exec $SHELL
```

4. **Install Python 3.7.x (e.g., 3.7.16)**

```bash
pyenv install 3.7.16
pyenv global 3.7.16   # or use pyenv local in your project folder
```

5. **Create and activate virtualenv**

```bash
python -m venv ~/.local/stow/steganogan-env
source ~/.local/stow/steganogan-env/bin/activate
```

6. **Install torch 1.1.0 manually**

```bash
wget https://download.pytorch.org/whl/cpu/torch-1.1.0-cp37-cp37m-linux_x86_64.whl
pip install torch-1.1.0-cp37-cp37m-linux_x86_64.whl
```

7. **Install steganogan**

```bash
pip install steganogan
```

GNU stow is optional, for better organize.
